# Generated by Django 3.2.2 on 2021-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='totprice',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='foodplans',
            field=models.ManyToManyField(blank=True, to='lifes.foodplan'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lives',
            field=models.ManyToManyField(blank=True, to='lifes.live'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='log',
            field=models.ManyToManyField(blank=True, to='lifes.logs'),
        ),
    ]
