# Generated by Django 3.0.5 on 2021-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.BigIntegerField()),
                ('otp', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'OTP',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobno',
            field=models.BigIntegerField(unique=True),
        ),
    ]
