# Generated by Django 3.0.5 on 2021-05-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subplans',
            name='plan',
            field=models.CharField(choices=[('Free Plan', 'Free Plan'), ('Basic Plan', 'Basic Plan'), ('Semi-Premium Plan', 'Semi-Premium Plan'), ('Premium Plan', 'Premium Plan')], max_length=100),
        ),
    ]
