# Generated by Django 3.2.2 on 2021-05-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streak',
            options={'verbose_name_plural': 'Streaks!'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='streaks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifes.streak'),
        ),
    ]
