# Generated by Django 3.2.2 on 2021-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0002_alter_bmi_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeecontrol',
            name='employeetype',
            field=models.CharField(choices=[('Nutritionist', 'Nutritionist'), ('Dietician', 'Dietician'), ('employee', 'employee'), ('trainee', 'trainee'), ('finance', 'finance')], max_length=100),
        ),
    ]
