# Generated by Django 3.0.5 on 2021-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0002_auto_20210602_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstore',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otpstore',
            name='passw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otpstore',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
