# Generated by Django 3.2.2 on 2021-05-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0002_auto_20210511_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Breakfast', to='lifes.foodplan'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dinner', to='lifes.foodplan'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lunch', to='lifes.foodplan'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='snacks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Snacks', to='lifes.foodplan'),
        ),
    ]
