# Generated by Django 3.0.5 on 2021-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0003_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=50),
        ),
    ]
