# Generated by Django 3.2.2 on 2021-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0003_auto_20210515_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
