# Generated by Django 3.0.5 on 2021-06-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0003_auto_20210602_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='quantuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('serving', models.IntegerField(default=1)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('meal', models.CharField(choices=[('preworkout', 'preworkout'), ('postworkout', 'postworkout'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('dinner', 'dinner')], max_length=50)),
                ('foodit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifes.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quantity Of Food!',
            },
        ),
    ]
