# Generated by Django 3.0.5 on 2021-05-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0004_dietplan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifes.subplans'),
        ),
    ]
