# Generated by Django 3.2.2 on 2021-05-16 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0004_alter_contact_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='bmr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BMR INDEX',
            },
        ),
    ]
