# Generated by Django 3.2.2 on 2021-05-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0004_auto_20210511_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifes.subplans', to_field='plan'),
        ),
        migrations.AlterField(
            model_name='subplans',
            name='plan',
            field=models.CharField(choices=[('Free Plan', 'Free Plan'), ('Basic Plan', 'Basic Plan'), ('Premium Plan', 'Premium Plan')], max_length=100, unique=True),
        ),
    ]
