# Generated by Django 3.2.2 on 2021-05-11 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0005_auto_20210511_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='subplans',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subplans',
            name='plan',
            field=models.CharField(choices=[('Free Plan', 'Free Plan'), ('Basic Plan', 'Basic Plan'), ('Premium Plan', 'Premium Plan')], max_length=100),
        ),
    ]
