# Generated by Django 3.2.2 on 2021-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0005_bmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='allot',
            field=models.BooleanField(default=False),
        ),
    ]
