# Generated by Django 3.0.5 on 2021-05-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0005_auto_20210524_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='foodplans',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='diets',
        ),
        migrations.AddField(
            model_name='myuser',
            name='diets',
            field=models.ManyToManyField(blank=True, to='lifes.dietplan'),
        ),
    ]
