# Generated by Django 3.0.5 on 2021-06-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0006_auto_20210604_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='extra',
        ),
    ]
