# Generated by Django 3.0.5 on 2021-05-26 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0006_auto_20210527_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10000)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifes.dietplan')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifes.employeecontrol')),
                ('us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
