# Generated by Django 3.2.2 on 2021-05-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0007_alter_grocerylist_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='invoicepdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
