# Generated by Django 3.2.2 on 2021-05-11 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0007_alter_subplans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplans',
            name='allot',
            field=models.ManyToManyField(blank=True, related_name='Alloted_Subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subplans',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
