# Generated by Django 3.0.5 on 2021-06-04 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0007_remove_logger_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner', to='lifes.foodplan')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch', to='lifes.foodplan')),
                ('postworkout', models.ManyToManyField(blank=True, related_name='Post_work', to='lifes.foodplan')),
                ('preworkout', models.ManyToManyField(blank=True, related_name='Pre_work', to='lifes.foodplan')),
                ('snacks', models.ManyToManyField(blank=True, related_name='snack', to='lifes.foodplan')),
            ],
            options={
                'verbose_name_plural': 'Log Meals!',
            },
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='log',
        ),
        migrations.DeleteModel(
            name='logger',
        ),
        migrations.AddField(
            model_name='logs',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
