# Generated by Django 3.0.5 on 2021-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0008_auto_20210527_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
