# Generated by Django 3.0.5 on 2021-06-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0008_auto_20210605_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='quantyrepssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantsets', models.IntegerField(default=1)),
                ('quantreps', models.IntegerField(default=1)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('exername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifes.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quantity of sets and reps!',
            },
        ),
    ]
