# Generated by Django 3.2.2 on 2021-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0008_auto_20210511_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bill',
            field=models.ManyToManyField(blank=True, to='lifes.bills'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='height',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='target',
            field=models.CharField(blank=True, choices=[('Gain Weight', 'Gain Weight'), ('Stay Fit', 'Stay Fit'), ('Loose Weight', 'Loose Weight')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weight',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
