# Generated by Django 3.2.2 on 2021-05-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0008_alter_bills_invoicepdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'verbose_name_plural': 'Check Live Meetings!'},
        ),
        migrations.RemoveField(
            model_name='live',
            name='link',
        ),
    ]
