# Generated by Django 3.0.5 on 2021-05-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0009_bills_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestchange',
            options={'verbose_name_plural': 'User Requests'},
        ),
        migrations.DeleteModel(
            name='grocerylist',
        ),
    ]
