# Generated by Django 3.0.5 on 2021-05-27 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0010_auto_20210527_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='grocerylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billitem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifes.bills')),
                ('groid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, to='lifes.food')),
            ],
            options={
                'verbose_name_plural': 'Current Grocery Lists!',
            },
        ),
    ]
