# Generated by Django 3.0.5 on 2021-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0012_auto_20210528_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobno',
            field=models.BigIntegerField(unique=True),
        ),
    ]
