# Generated by Django 3.0.5 on 2021-05-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0013_auto_20210528_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(default='defaultpic.jpg', upload_to='profilepics/'),
        ),
    ]
