# Generated by Django 3.0.5 on 2021-06-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0013_auto_20210609_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='steps',
        ),
        migrations.AddField(
            model_name='myuser',
            name='steps',
            field=models.ManyToManyField(blank=True, to='lifes.step'),
        ),
    ]
