# Generated by Django 3.0.5 on 2021-06-08 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0014_auto_20210609_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fordiet',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='forfit',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fornut',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
