# Generated by Django 3.0.5 on 2021-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0014_myuser_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(default='profilepics/defaultpic.jpg', upload_to='profilepics/'),
        ),
    ]
