# Generated by Django 3.0.5 on 2021-05-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0015_auto_20210530_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(default='defaultpic.jpg', upload_to=''),
        ),
    ]
