# Generated by Django 3.0.5 on 2021-06-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0016_auto_20210530_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_path', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Equipment!',
            },
        ),
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(max_length=100)),
                ('muscle_worked', models.CharField(max_length=100)),
                ('video_path', models.URLField(blank=True, null=True)),
                ('image_path', models.URLField(blank=True, null=True)),
                ('equipments', models.ManyToManyField(blank=True, to='lifes.equipment')),
            ],
            options={
                'verbose_name_plural': 'Manage Exercises!',
            },
        ),
        migrations.CreateModel(
            name='exerciseplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('exercisename', models.ManyToManyField(related_name='Exercise', to='lifes.exercise')),
            ],
            options={
                'verbose_name_plural': 'Manage Excercise PLans Issued!',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='fitness',
            field=models.ManyToManyField(blank=True, to='lifes.exerciseplan'),
        ),
    ]
